### ISSUE TITLE
z-image训练时报错

### ISSUE THREAD

**Issue by dingyuandu** [TianDongL/Diffusion_pipe_in_ComfyUI#7]
Training [rank0]: RuntimeError: split_with_sizes expects split_sizes to sum exactly to 105 (input tensor's size at dimension 0), but got split_sizes=[32, 32]
Training [rank0]:[W107 18:04:39.888302616 ProcessGroupNCCL.cpp:1479] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

**Comment by TianDongL** [comment]
你能贴出完整的配置文件和报错信息吗

**Comment by dingyuandu** [comment]
报错日志：
[2026-01-07 16:31:49,359] [INFO] [logging.py:107:log_dist] [Rank 0] Using client callable to create basic optimizer
[2026-01-07 16:31:49,359] [INFO] [logging.py:107:log_dist] [Rank 0] Removing param_group that has no 'params' in the basic Optimizer
[2026-01-07 16:31:49,476] [INFO] [logging.py:107:log_dist] [Rank 0] DeepSpeed Basic Optimizer = AdamW8bitKahan
[2026-01-07 16:31:49,476] [INFO] [logging.py:107:log_dist] [Rank 0] DeepSpeed Final Optimizer = AdamW8bitKahan
FETCH ComfyRegistry Data [DONE]
[ComfyUI-Manager] default cache updated: https://api.comfy.org/nodes
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
[ComfyUI-Manager] All startup tasks have been completed.
Training /home/bud.he/.conda/envs/comfyui_DP/lib/python3.12/site-packages/torch/_inductor/lowering.py:1917: UserWarning: Torchinductor does not support code generation for complex operators. Performance may be worse than eager.
Training   warnings.warn(
Training [rank0]: Traceback (most recent call last):
Training [rank0]:   File "/DATA/GPU-files/15.79/ComfyUI/custom_nodes/Diffusion_pipe_in_ComfyUI/train.py", line 842, in <module>
Training [rank0]:     loss = model_engine.train_batch(iterator).item()
Training [rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Training [rank0]:   File "/home/bud.he/.conda/envs/comfyui_DP/lib/python3.12/site-packages/deepspeed/runtime/pipe/engine.py", line 389, in train_batch
Training [rank0]:     self._exec_schedule(sched)
Training [rank0]:   File "/home/bud.he/.conda/envs/comfyui_DP/lib/python3.12/site-packages/deepspeed/runtime/pipe/engine.py", line 1423, in _exec_schedule
Training [rank0]:     self._exec_instr(**cmd.kwargs)
Training [rank0]:   File "/home/bud.he/.conda/envs/comfyui_DP/lib/python3.12/site-packages/deepspeed/runtime/pipe/engine.py", line 736, in _exec_forward_pass
Training [rank0]:     outputs = super().forward(inputs)
Training [rank0]:               ^^^^^^^^^^^^^^^^^^^^^^^
Training [rank0]:   File "/home/bud.he/.conda/envs/comfyui_DP/lib/python3.12/site-packages/deepspeed/utils/nvtx.py", line 20, in wrapped_fn
Training [rank0]:     ret_val = func(*args, **kwargs)
Training [rank0]:               ^^^^^^^^^^^^^^^^^^^^^
Training [rank0]:   File "/home/bud.he/.conda/envs/comfyui_DP/lib/python3.12/site-packages/deepspeed/runtime/engine.py", line 2063, in forward
Training [rank0]:     loss = self.module(*inputs, **kwargs)
Training [rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Training [rank0]:   File "/home/bud.he/.conda/envs/comfyui_DP/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
Training [rank0]:     return self._call_impl(*args, **kwargs)
Training [rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Training [rank0]:   File "/home/bud.he/.conda/envs/comfyui_DP/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1857, in _call_impl
Training [rank0]:     return inner()
Training [rank0]:            ^^^^^^^
Training [rank0]:   File "/home/bud.he/.conda/envs/comfyui_DP/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1805, in inner
Training [rank0]:     result = forward_call(*args, **kwargs)
Training [rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Training [rank0]:   File "/home/bud.he/.conda/envs/comfyui_DP/lib/python3.12/site-packages/deepspeed/runtime/pipe/module.py", line 390, in forward
Training [rank0]:     x = exec_range_func(start_idx, end_idx)(*x)
Training [rank0]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Training [rank0]:   File "/home/bud.he/.conda/envs/comfyui_DP/lib/python3.12/site-packages/deepspeed/runtime/pipe/module.py", line 365, in exec_func
Training [rank0]:     inputs = layer(inputs)
Training [rank0]:              ^^^^^^^^^^^^^
Training [rank0]:   File "/home/bud.he/.conda/envs/comfyui_DP/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1749, in _wrapped_call_impl
Training [rank0]:     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
Training [rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Training [rank0]:   File "/home/bud.he/.conda/envs/comfyui_DP/lib/python3.12/site-packages/torch/_dynamo/eval_frame.py", line 655, in _fn
Training [rank0]:     return fn(*args, **kwargs)
Training [rank0]:            ^^^^^^^^^^^^^^^^^^^
Training [rank0]:   File "/home/bud.he/.conda/envs/comfyui_DP/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
Training [rank0]:     return forward_call(*args, **kwargs)
Training [rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Training [rank0]:   File "/home/bud.he/.conda/envs/comfyui_DP/lib/python3.12/site-packages/torch/amp/autocast_mode.py", line 44, in decorate_autocast
Training [rank0]:     return func(*args, **kwargs)
Training [rank0]:            ^^^^^^^^^^^^^^^^^^^^^
Training [rank0]:   File "/DATA/GPU-files/15.79/ComfyUI/custom_nodes/Diffusion_pipe_in_ComfyUI/models/z_image.py", line 634, in forward
Training [rank0]:     cap_freqs_cis = list(self.rope_embedder(torch.cat(cap_pos_ids, dim=0)).split(cap_item_seqlens, dim=0))
Training [rank0]:                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Training [rank0]:   File "/home/bud.he/.conda/envs/comfyui_DP/lib/python3.12/site-packages/torch/_tensor.py", line 1053, in split
Training [rank0]:     return torch._VF.split_with_sizes(self, split_size, dim)
Training [rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Training [rank0]: RuntimeError: split_with_sizes expects split_sizes to sum exactly to 105 (input tensor's size at dimension 0), but got split_sizes=[32, 32]
Training [rank0]:[W107 16:32:08.532338151 ProcessGroupNCCL.cpp:1479] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())
[2026-01-07 16:32:15,719] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 3100561
[2026-01-07 16:32:15,720] [ERROR] [launch.py:325:sigkill_handler] ['/home/bud.he/.conda/envs/comfyui_DP/bin/python3.12', '-u', '/DATA/GPU-files/15.79/ComfyUI/custom_nodes/Diffusion_pipe_in_ComfyUI/train.py', '--local_rank=0', '--deepspeed', '--config', '/DATA/GPU-files/15.79/ComfyUI/custom_nodes/Diffusion_pipe_in_ComfyUI/train_config/trainconfig.toml', '--regenerate_cache'] exits with return code = 1

**Comment by TianDongL** [comment]
<img width="561" height="719" alt="Image" src="https://github.com/user-attachments/assets/e79c727f-ffc9-4737-9052-7a3c63ff35c8" />zimage暂时不支持编译模型，你把这个关了就好了

**Comment by dingyuandu** [comment]
ok
已解决   谢谢
